// LeetCode topic tags — { slug, label }
export const TOPICS = [
  { slug: 'array', label: 'Array' },
  { slug: 'string', label: 'String' },
  { slug: 'hash-table', label: 'Hash Table' },
  { slug: 'dynamic-programming', label: 'Dynamic Programming' },
  { slug: 'math', label: 'Math' },
  { slug: 'sorting', label: 'Sorting' },
  { slug: 'greedy', label: 'Greedy' },
  { slug: 'depth-first-search', label: 'Depth-First Search' },
  { slug: 'binary-search', label: 'Binary Search' },
  { slug: 'breadth-first-search', label: 'Breadth-First Search' },
  { slug: 'tree', label: 'Tree' },
  { slug: 'matrix', label: 'Matrix' },
  { slug: 'two-pointers', label: 'Two Pointers' },
  { slug: 'bit-manipulation', label: 'Bit Manipulation' },
  { slug: 'stack', label: 'Stack' },
  { slug: 'heap-priority-queue', label: 'Heap / Priority Queue' },
  { slug: 'graph', label: 'Graph' },
  { slug: 'sliding-window', label: 'Sliding Window' },
  { slug: 'linked-list', label: 'Linked List' },
  { slug: 'backtracking', label: 'Backtracking' },
  { slug: 'trie', label: 'Trie' },
  { slug: 'binary-tree', label: 'Binary Tree' },
  { slug: 'recursion', label: 'Recursion' },
  { slug: 'divide-and-conquer', label: 'Divide and Conquer' },
]
